/**
 * @fileoverview Autognosis → SelfModificationEngine Bridge
 *
 * Closed-loop wiring: L4 evolution directives from the AutgnosisEngine
 * feed into the SelfModificationEngine's ENACTION phase, enabling
 * genuine self-improving autonomy with safety bounds.
 *
 * Data Flow:
 *   AutgnosisEngine.runCycle()
 *     → L3 recurring insights accumulate
 *       → L4 evolution directives generated
 *         → Bridge translates directive → ModificationRequest
 *           → SelfModificationEngine.proposeModification(request)
 *             → Safety check (dead man's switch, rate limit, delta bounds)
 *               → If SAFE: apply modification
 *               → If UNSAFE: log rejection, emit telemetry
 *                 → Telemetry feeds back to AutgnosisEngine (L0)
 *
 * Composition: /echo-master wiring-pattern §1
 */

import { EventEmitter } from 'events';

// ─── Types ─────────────────────────────────────────────────────

/** Autognosis levels (L0-L4) */
export enum AutgnosisLevel {
  L0_MONITORING = 0,    // Raw metric observation
  L1_PATTERN = 1,       // Pattern detection across metrics
  L2_INSIGHT = 2,       // Causal insight formation
  L3_RECURRING = 3,     // Recurring insight consolidation
  L4_EVOLUTION = 4,     // Self-modification directives
}

/** An insight generated by the autognosis engine */
export interface AutgnosisInsight {
  id: string;
  level: AutgnosisLevel;
  timestamp: number;
  category: 'reservoir' | 'readout' | 'echobeats' | 'endocrine' | 'memory' | 'identity';
  pattern: string;           // Human-readable description
  metric_key: string;        // Which metric triggered this
  metric_value: number;      // Current value
  metric_target: number;     // Desired value
  confidence: number;        // 0-1
  recurrence_count: number;  // How many times this pattern appeared
}

/** An L4 evolution directive — the bridge's primary input */
export interface EvolutionDirective {
  id: string;
  timestamp: number;
  source_insights: string[];  // IDs of L3 insights that generated this
  target_parameter: string;   // Key in SelfModificationEngine
  proposed_delta: number;     // How much to change
  rationale: string;          // Why this change
  confidence: number;         // 0-1
  urgency: number;            // 0-1 (higher = more urgent)
}

/** Bridge configuration */
export interface BridgeConfig {
  /** Minimum confidence for a directive to be forwarded (default: 0.6) */
  minConfidence: number;
  /** Minimum recurrence count for L3→L4 promotion (default: 3) */
  minRecurrence: number;
  /** Maximum directives per Echobeats cycle (default: 2) */
  maxDirectivesPerCycle: number;
  /** Cooldown between modifications to same parameter (ms, default: 60000) */
  parameterCooldown: number;
  /** Whether to log all decisions for audit trail (default: true) */
  auditLog: boolean;
  /** Coherence threshold below which all modifications are blocked (default: 0.3) */
  coherenceFloor: number;
}

/** Result of attempting to forward a directive */
export interface ForwardResult {
  directive_id: string;
  accepted: boolean;
  reason: string;
  modification_applied?: {
    parameter: string;
    old_value: number;
    new_value: number;
    delta: number;
  };
  safety_flags: string[];
}

/** Audit log entry */
export interface AuditEntry {
  timestamp: number;
  type: 'directive_received' | 'directive_forwarded' | 'directive_blocked' | 'modification_applied' | 'modification_rejected' | 'safety_triggered';
  directive_id: string;
  details: Record<string, unknown>;
}

// ─── Autognosis Engine (Embedded L0-L4) ────────────────────────

/**
 * Lightweight autognosis engine that processes raw metrics through
 * 5 levels of self-awareness to produce evolution directives.
 */
export class AutgnosisEngine {
  private insights: Map<string, AutgnosisInsight> = new Map();
  private patterns: Map<string, number> = new Map(); // pattern hash → count
  private cycleCount = 0;

  /** L0: Observe raw metrics */
  observeMetrics(metrics: Record<string, number>): AutgnosisInsight[] {
    const l0Insights: AutgnosisInsight[] = [];
    for (const [key, value] of Object.entries(metrics)) {
      const insight: AutgnosisInsight = {
        id: `l0-${key}-${this.cycleCount}`,
        level: AutgnosisLevel.L0_MONITORING,
        timestamp: Date.now(),
        category: this.categorizeMetric(key),
        pattern: `${key} = ${value.toFixed(4)}`,
        metric_key: key,
        metric_value: value,
        metric_target: this.getTarget(key),
        confidence: 1.0,
        recurrence_count: 0,
      };
      l0Insights.push(insight);
      this.insights.set(insight.id, insight);
    }
    return l0Insights;
  }

  /** L1: Detect patterns across metrics */
  detectPatterns(l0: AutgnosisInsight[]): AutgnosisInsight[] {
    const l1: AutgnosisInsight[] = [];
    // Detect drift patterns (metric consistently away from target)
    for (const obs of l0) {
      const drift = obs.metric_value - obs.metric_target;
      if (Math.abs(drift) > 0.1) {
        const pattern = `${obs.category}:${drift > 0 ? 'high' : 'low'}:${obs.metric_key}`;
        const count = (this.patterns.get(pattern) || 0) + 1;
        this.patterns.set(pattern, count);
        l1.push({
          ...obs,
          id: `l1-${pattern}-${this.cycleCount}`,
          level: AutgnosisLevel.L1_PATTERN,
          pattern: `${obs.metric_key} drifting ${drift > 0 ? 'above' : 'below'} target by ${Math.abs(drift).toFixed(3)}`,
          confidence: Math.min(count / 5, 1.0),
          recurrence_count: count,
        });
      }
    }
    return l1;
  }

  /** L2: Form causal insights */
  formInsights(l1: AutgnosisInsight[]): AutgnosisInsight[] {
    const l2: AutgnosisInsight[] = [];
    // Group by category and look for correlated patterns
    const byCategory = new Map<string, AutgnosisInsight[]>();
    for (const p of l1) {
      const arr = byCategory.get(p.category) || [];
      arr.push(p);
      byCategory.set(p.category, arr);
    }
    for (const [cat, patterns] of byCategory) {
      if (patterns.length >= 2) {
        const avgConfidence = patterns.reduce((s, p) => s + p.confidence, 0) / patterns.length;
        l2.push({
          id: `l2-${cat}-${this.cycleCount}`,
          level: AutgnosisLevel.L2_INSIGHT,
          timestamp: Date.now(),
          category: cat as AutgnosisInsight['category'],
          pattern: `Correlated drift in ${cat}: ${patterns.map(p => p.metric_key).join(', ')}`,
          metric_key: patterns[0].metric_key,
          metric_value: patterns[0].metric_value,
          metric_target: patterns[0].metric_target,
          confidence: avgConfidence,
          recurrence_count: Math.max(...patterns.map(p => p.recurrence_count)),
        });
      }
    }
    return l2;
  }

  /** L3: Consolidate recurring insights */
  consolidateRecurring(l2: AutgnosisInsight[], minRecurrence: number): AutgnosisInsight[] {
    return l2
      .filter(i => i.recurrence_count >= minRecurrence)
      .map(i => ({
        ...i,
        id: `l3-${i.category}-${i.metric_key}-${this.cycleCount}`,
        level: AutgnosisLevel.L3_RECURRING,
        confidence: Math.min(i.confidence * 1.2, 1.0),
      }));
  }

  /** L4: Generate evolution directives from recurring insights */
  generateDirectives(l3: AutgnosisInsight[]): EvolutionDirective[] {
    const directives: EvolutionDirective[] = [];
    for (const insight of l3) {
      const delta = (insight.metric_target - insight.metric_value) * 0.1; // Conservative 10% correction
      const paramKey = this.mapToParameter(insight);
      if (paramKey) {
        directives.push({
          id: `l4-${paramKey}-${this.cycleCount}`,
          timestamp: Date.now(),
          source_insights: [insight.id],
          target_parameter: paramKey,
          proposed_delta: delta,
          rationale: `L3 recurring insight: ${insight.pattern}. Proposing ${delta > 0 ? '+' : ''}${delta.toFixed(4)} correction.`,
          confidence: insight.confidence,
          urgency: Math.min(insight.recurrence_count / 10, 1.0),
        });
      }
    }
    return directives;
  }

  /** Run a full L0→L4 cycle */
  runCycle(metrics: Record<string, number>, minRecurrence: number): EvolutionDirective[] {
    this.cycleCount++;
    const l0 = this.observeMetrics(metrics);
    const l1 = this.detectPatterns(l0);
    const l2 = this.formInsights(l1);
    const l3 = this.consolidateRecurring(l2, minRecurrence);
    return this.generateDirectives(l3);
  }

  private categorizeMetric(key: string): AutgnosisInsight['category'] {
    if (key.includes('reservoir') || key.includes('spectral') || key.includes('leak')) return 'reservoir';
    if (key.includes('readout') || key.includes('learning_rate')) return 'readout';
    if (key.includes('echobeat') || key.includes('phase') || key.includes('sync')) return 'echobeats';
    if (key.includes('cortisol') || key.includes('dopamine') || key.includes('serotonin') || key.includes('endocrine')) return 'endocrine';
    if (key.includes('memory') || key.includes('attention') || key.includes('forgetting')) return 'memory';
    return 'identity';
  }

  private getTarget(key: string): number {
    const targets: Record<string, number> = {
      reservoir_energy: 0.5, reservoir_coherence: 0.7, spectral_radius: 0.95,
      leak_rate: 0.3, readout_learning_rate: 0.001, echobeat_sync: 0.8,
      cortisol: 0.3, dopamine_tonic: 0.5, serotonin: 0.5,
      memory_active_ratio: 0.3, attention_threshold: 0.5,
      identity_coherence: 0.8, entropy_tolerance: 0.6,
    };
    return targets[key] ?? 0.5;
  }

  private mapToParameter(insight: AutgnosisInsight): string | null {
    const mapping: Record<string, string> = {
      reservoir_energy: 'spectral_radius', reservoir_coherence: 'leak_rate',
      spectral_radius: 'spectral_radius', leak_rate: 'leak_rate',
      readout_learning_rate: 'learning_rate',
      echobeat_sync: 'sync_threshold', phase_duration: 'phase_duration',
      cortisol: 'sensitivity_multiplier', dopamine_tonic: 'decay_rate',
      memory_active_ratio: 'attention_threshold', forgetting_rate: 'forgetting_rate',
      identity_coherence: 'coherence_target', entropy_tolerance: 'entropy_tolerance',
    };
    return mapping[insight.metric_key] ?? null;
  }
}

// ─── Bridge ────────────────────────────────────────────────────

/**
 * The Autognosis → SelfModification Bridge.
 *
 * Translates L4 evolution directives into ModificationRequests,
 * applies safety filtering, and forwards to the SelfModificationEngine.
 */
export class AutgnosisSelfModBridge extends EventEmitter {
  private config: BridgeConfig;
  private autgnosis: AutgnosisEngine;
  private auditLog: AuditEntry[] = [];
  private parameterCooldowns: Map<string, number> = new Map();
  private directivesThisCycle = 0;
  private currentCoherence = 0.7;

  // External references (set via wire())
  private selfModEngine: {
    proposeModification: (req: { key: string; delta: number; coherenceAtRequest: number; reason: string }) => { applied: boolean; reason: string; oldValue?: number; newValue?: number };
    getParameter: (key: string) => { value: number } | undefined;
    isInSafetyMode: () => boolean;
  } | null = null;

  constructor(config?: Partial<BridgeConfig>) {
    super();
    this.config = {
      minConfidence: 0.6,
      minRecurrence: 3,
      maxDirectivesPerCycle: 2,
      parameterCooldown: 60_000,
      auditLog: true,
      coherenceFloor: 0.3,
      ...config,
    };
    this.autgnosis = new AutgnosisEngine();
  }

  /** Wire the bridge to a SelfModificationEngine instance */
  wire(engine: {
    proposeModification: (req: { key: string; delta: number; coherenceAtRequest: number; reason: string }) => { applied: boolean; reason: string; oldValue?: number; newValue?: number };
    getParameter: (key: string) => { value: number } | undefined;
    isInSafetyMode: () => boolean;
  }): void {
    this.selfModEngine = engine;
    this.emit('wired');
  }

  /** Update current coherence (called by telemetry shell) */
  updateCoherence(coherence: number): void {
    this.currentCoherence = coherence;
  }

  /**
   * Run a full closed-loop cycle:
   *   metrics → L0→L4 → filter → propose → apply/reject → audit
   */
  runClosedLoop(metrics: Record<string, number>): ForwardResult[] {
    if (!this.selfModEngine) {
      throw new Error('Bridge not wired. Call wire(engine) first.');
    }

    this.directivesThisCycle = 0;
    const results: ForwardResult[] = [];

    // Run autognosis L0→L4
    const directives = this.autgnosis.runCycle(metrics, this.config.minRecurrence);

    // Sort by urgency * confidence (highest priority first)
    directives.sort((a, b) => (b.urgency * b.confidence) - (a.urgency * a.confidence));

    for (const directive of directives) {
      this.audit('directive_received', directive.id, { directive });

      // Safety gate 1: Coherence floor
      if (this.currentCoherence < this.config.coherenceFloor) {
        const result = this.block(directive, `Coherence ${this.currentCoherence.toFixed(3)} below floor ${this.config.coherenceFloor}`, ['coherence_floor']);
        results.push(result);
        continue;
      }

      // Safety gate 2: SelfMod engine in safety mode
      if (this.selfModEngine.isInSafetyMode()) {
        const result = this.block(directive, 'SelfModificationEngine in safety mode (dead man switch active)', ['dead_man_switch']);
        results.push(result);
        continue;
      }

      // Safety gate 3: Confidence threshold
      if (directive.confidence < this.config.minConfidence) {
        const result = this.block(directive, `Confidence ${directive.confidence.toFixed(3)} below threshold ${this.config.minConfidence}`, ['low_confidence']);
        results.push(result);
        continue;
      }

      // Safety gate 4: Rate limit per cycle
      if (this.directivesThisCycle >= this.config.maxDirectivesPerCycle) {
        const result = this.block(directive, `Rate limit: ${this.config.maxDirectivesPerCycle} directives per cycle exceeded`, ['rate_limit']);
        results.push(result);
        continue;
      }

      // Safety gate 5: Parameter cooldown
      const lastMod = this.parameterCooldowns.get(directive.target_parameter) || 0;
      if (Date.now() - lastMod < this.config.parameterCooldown) {
        const remaining = this.config.parameterCooldown - (Date.now() - lastMod);
        const result = this.block(directive, `Parameter ${directive.target_parameter} on cooldown (${remaining}ms remaining)`, ['parameter_cooldown']);
        results.push(result);
        continue;
      }

      // Safety gate 6: Parameter exists
      const param = this.selfModEngine.getParameter(directive.target_parameter);
      if (!param) {
        const result = this.block(directive, `Parameter ${directive.target_parameter} not found in SelfModificationEngine`, ['unknown_parameter']);
        results.push(result);
        continue;
      }

      // All gates passed — forward to SelfModificationEngine
      this.audit('directive_forwarded', directive.id, { target: directive.target_parameter, delta: directive.proposed_delta });

      const modResult = this.selfModEngine.proposeModification({
        key: directive.target_parameter,
        delta: directive.proposed_delta,
        coherenceAtRequest: this.currentCoherence,
        reason: directive.rationale,
      });

      if (modResult.applied) {
        this.directivesThisCycle++;
        this.parameterCooldowns.set(directive.target_parameter, Date.now());
        const forwardResult: ForwardResult = {
          directive_id: directive.id,
          accepted: true,
          reason: 'Modification applied successfully',
          modification_applied: {
            parameter: directive.target_parameter,
            old_value: modResult.oldValue ?? param.value,
            new_value: modResult.newValue ?? (param.value + directive.proposed_delta),
            delta: directive.proposed_delta,
          },
          safety_flags: [],
        };
        this.audit('modification_applied', directive.id, forwardResult.modification_applied!);
        this.emit('modification_applied', forwardResult);
        results.push(forwardResult);
      } else {
        const forwardResult: ForwardResult = {
          directive_id: directive.id,
          accepted: false,
          reason: `SelfModificationEngine rejected: ${modResult.reason}`,
          safety_flags: ['engine_rejected'],
        };
        this.audit('modification_rejected', directive.id, { reason: modResult.reason });
        this.emit('modification_rejected', forwardResult);
        results.push(forwardResult);
      }
    }

    this.emit('cycle_complete', { results, directiveCount: directives.length, appliedCount: this.directivesThisCycle });
    return results;
  }

  private block(directive: EvolutionDirective, reason: string, flags: string[]): ForwardResult {
    const result: ForwardResult = { directive_id: directive.id, accepted: false, reason, safety_flags: flags };
    this.audit('directive_blocked', directive.id, { reason, flags });
    this.emit('directive_blocked', result);
    return result;
  }

  private audit(type: AuditEntry['type'], directiveId: string, details: Record<string, unknown>): void {
    if (!this.config.auditLog) return;
    const entry: AuditEntry = { timestamp: Date.now(), type, directive_id: directiveId, details };
    this.auditLog.push(entry);
    if (this.auditLog.length > 1000) this.auditLog.splice(0, 500);
  }

  /** Get audit log (most recent first) */
  getAuditLog(limit = 100): AuditEntry[] {
    return this.auditLog.slice(-limit).reverse();
  }

  /** Get bridge state for telemetry */
  getState(): Record<string, unknown> {
    return {
      wired: !!this.selfModEngine,
      currentCoherence: this.currentCoherence,
      directivesThisCycle: this.directivesThisCycle,
      cooldownsActive: this.parameterCooldowns.size,
      auditLogSize: this.auditLog.length,
      config: this.config,
    };
  }
}

// ─── Factory ───────────────────────────────────────────────────

/** Create and wire the autognosis-selfmod bridge */
export function createAutgnosisSelfModBridge(
  selfModEngine: Parameters<AutgnosisSelfModBridge['wire']>[0],
  config?: Partial<BridgeConfig>,
): AutgnosisSelfModBridge {
  const bridge = new AutgnosisSelfModBridge(config);
  bridge.wire(selfModEngine);
  return bridge;
}
